<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Brand Devices' => 'Marcas de dispositivos',
    'Cars' => 'Vehiculos',
    'Configuracions' => 'Configuraciones',
    'Create Brand Device' => 'Crear Marca',
    'Create Car' => 'Crear Vehiculo',
    'Create Configuracion' => 'Crear configuracion',
    'Create Device' => 'Crear dispositivo',
    'Create Video' => 'Crear video',
    'Devices' => 'Dispositivos',
    'Videos' => 'Videos',
    '{modelClass} ' => '',
    'Created At' => 'Fecha Creación',
    'Description' => 'Descripción',
    'Name' => 'Nombre',
    'Title' => 'Titulo',
    'Typereport ID' => 'Tipo',
    'Url' => 'URL',
    'Are you sure you want to delete this item?' => 'Seguro que desea eliminar el item?',
    'Create' => 'Crear',
    'Create Report' => 'Crear Noticia',
    'Create Server' => 'Crear Servidor',
    'Create User' => 'Crear Usuario',
    'Delete' => 'Eliminar',
    'Reports' => 'Noticias',
    'Reset' => 'Resetear',
    'Search' => 'Buscar',
    'Select...' => 'Seleccionar..',
    'Servers' => 'Servidores',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Users' => 'Usuarios',
];
