<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '+ Vehiculo' => '',
    'server_id' => 'Servidor',
    '{modelClass} ' => '',
    'Active' => 'Activo',
    'Are you sure you want to delete this item?' => '¿Seguro que desea eliminar?',
    'Brand Devices' => 'Marca',
    'Brand ID' => 'Marca',
    'Cars' => 'Vehiculos',
    'Configuracions' => 'Configuraciones',
    'Create' => 'Crear',
    'Create Brand Device' => 'Crear Marca',
    'Create Car' => 'Crear Vehiculo',
    'Create Configuracion' => 'Crear Configuración',
    'Create Device' => 'Crear Dispositivo',
    'Create Report' => 'Crear Novedad',
    'Create Server' => 'Crear Servidor',
    'Create User' => 'Crear Usuario',
    'Create Video' => 'Crear Video',
    'Created At' => 'Fecha de creación',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Device ID' => 'Dispositivo',
    'Devices' => 'Dispositivos',
    'ID' => 'ID',
    'Ip' => 'IP',
    'Licence' => 'Licencia',
    'Link Youtube' => 'Link Youtube',
    'Name' => 'Nombre',
    'Off  Ibutton' => 'OFF IBUTTON',
    'On  Ibutton' => 'ON IBUTTON',
    'Order' => 'Orden',
    'Report ID' => 'Reporte',
    'Reports' => 'Novedades',
    'Reset' => 'Resetear',
    'Reset  Gps' => 'RESETEAR GPS',
    'Rol' => 'Rol',
    'Search' => 'Buscar',
    'Select...' => 'Seleccionar...',
    'Server ID' => 'Servidor',
    'Servers' => 'Servidores',
    'Telephone Number' => 'Telefono',
    'Title' => 'Titulo',
    'Typereport ID' => 'Tipo de novedad',
    'URL' => 'URL',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Url' => 'URL',
    'User ID' => 'Usuario',
    'Username' => 'Usuario',
    'Users' => 'Usuarios',
    'Value' => 'Valor',
    'Videos' => 'Videos',
];
